mvc/Models/ErrorViewModel.cs
namespace mvc.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

mvc/Models/HazirlikDbContext.cs
using Microsoft.EntityFrameworkCore;

namespace mvc.Models
{
    public class HazirlikDbContext : DbContext
    {
        string baglantiCumlesi = "Data Source=(localdb)\\MSSQLLocalDB;Initial Catalog=HazirlikDb;Integrated Security=True;Connect Timeout=30;Encrypt=False;Trust Server Certificate=False;Application Intent=ReadWrite;Multi Subnet Failover=False";
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(baglantiCumlesi);
        }
        public DbSet<Ogrenci> Ogrenciler { get; set; }
        public DbSet<Sinif> Siniflar { get; set; }
    }
}

mvc/Models/Ogrenci.cs
namespace mvc.Models
{
    public class Ogrenci
    {
        public string OgrenciAdi { get; set; }
        public int OgrenciId { get; set; }
        public string OgrenciSoyadi { get; set; }

        public Sinif? Sinif { get; set; }
        public int? SinifId { get; set; }
    }
}

mvc/Models/OgrenciSinifModel.cs
namespace mvc.Models
{
    public class OgrenciSinifModel
    {
        public string OgrenciAdi { get; set; }
        public int OgrenciId { get; set; }
        public string OgrenciSoyadi { get; set; }

        public string? SinifAdi { get; set; }
        public int SinifKodu { get; set; }
    }
}

mvc/Models/Sinif.cs
namespace mvc.Models
{
    public class Sinif
    {
        public int SinifId { get; set; }
        public string SinifAdi { get; set; }
        public int SinifKodu { get; set; }

        public ICollection<Ogrenci> Ogrenciler { get; set; }
    }
}

mvc/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using mvc.Models;
using System.Diagnostics;

namespace mvc.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

mvc/Controllers/OgrenciController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using mvc.Models;

namespace mvc.Controllers
{
    public class OgrenciController : Controller
    {
        HazirlikDbContext veritabani = new HazirlikDbContext();
        public IActionResult Index()
        {
            var liste = from ogrenci in veritabani.Ogrenciler
                        join Sinif in veritabani.Siniflar on ogrenci.SinifId
                        equals Sinif.SinifId
                        select new OgrenciSinifModel
                        {
                            OgrenciId = ogrenci.OgrenciId,
                            OgrenciAdi = ogrenci.OgrenciAdi,
                            OgrenciSoyadi = ogrenci.OgrenciSoyadi,
                            SinifAdi = Sinif.SinifAdi,
                            SinifKodu = Sinif.SinifKodu,

                        };
            return View(liste.ToList());
        }
        public IActionResult Guncelle(int id)
        {
            var sorgu = veritabani.Siniflar.ToList();
            ViewBag.siniflistesi = new SelectList(sorgu, "SinifId","SinifAdi");
            var ogrenci = veritabani.Ogrenciler.Find(id);
            return View(ogrenci);
        }
        [HttpPost]
        public IActionResult Guncelle(Ogrenci ogrenci)
        {
            veritabani.Entry<Ogrenci>(ogrenci).State = Microsoft.EntityFrameworkCore.EntityState.Modified;
            veritabani.SaveChanges();
            return RedirectToAction("Index");
        }
        public IActionResult Sil(int? id)
        {
            Ogrenci ogrenci = veritabani.Ogrenciler.Find(id);
            veritabani.Ogrenciler.Remove(ogrenci);
            veritabani.SaveChanges();

            return RedirectToAction("Index");
        }
        public IActionResult Ekle()
        {
            var SinifListesi = veritabani.Siniflar.ToList();
            ViewBag.SinifListesi = new SelectList(SinifListesi, "SinifId", "SinifAdi");
            return View();
        }
        [HttpPost]
        public IActionResult Ekle(Ogrenci ogrenci)
        {
            var siniflistesi = veritabani.Siniflar.ToList();
            ViewBag.siniflistesi = new SelectList(siniflistesi, "SinifId", "SinifAdi");
            ogrenci.SinifId = 2002;
            veritabani.Ogrenciler.Add(ogrenci);
            veritabani.SaveChanges();
            return RedirectToAction("Index");

        }
    }
}

mvc/Controllers/SinifController.cs
using Microsoft.AspNetCore.Mvc;
using mvc.Models;

namespace mvc.Controllers
{
    public class SinifController : Controller
    {
        HazirlikDbContext veritabani = new HazirlikDbContext();
        public IActionResult Index()
        {
            return View(veritabani.Siniflar.ToList());
        }
        public IActionResult Guncelle(int id)
        {
            Sinif sinif = veritabani.Siniflar.Find(id);
            return View(sinif);
        }
        [HttpPost]
        public IActionResult Guncelle(Sinif sinif)
        {
            veritabani.Entry<Sinif>(sinif).State = Microsoft.EntityFrameworkCore.EntityState.Modified;
            veritabani.SaveChanges();
            return RedirectToAction("Index");
        }
        public IActionResult Sil(int? id)
        {
            Sinif sinif = veritabani.Siniflar.Find(id);
            veritabani.Siniflar.Remove(sinif);
            veritabani.SaveChanges();

            return RedirectToAction("Index");
        }
        public IActionResult Ekle() 
        { 
            return View();
        }
        [HttpPost]
        public IActionResult Ekle(Sinif sinif)
        {
            veritabani.Siniflar.Add(sinif);
            veritabani.SaveChanges();
            return RedirectToAction("Index");

        }
    }
}

mvc/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

mvc/Views/Ogrenci/Ekle.cshtml
@model Ogrenci

<form asp-controller="Ogrenci" asp-action="Ekle" method="post">
    <div asp-validation-summary="All"></div>
    <div class="form-group">
        <label asp-for="OgrenciAdi"></label>
        <input asp-for="OgrenciAdi" class="form-control">
    </div>
    <div class="form-group">
        <label asp-for="OgrenciSoyadi"></label>
        <input asp-for="OgrenciSoyadi" class="form-control">
    </div>
    <div class="form-group">
        <label asp-for="SinifId"></label>
        <select name="SinifId" class="form-control" asp-items="@(new SelectList(ViewBag.sinifListesi,"Value","Text"))">
            <option value="">Bir Sınıf Seçiniz

            </option>
        </select>
    </div>
    <div class="form-group">
        <button type="submit" class="btn btn-success">Kaydet</button>
    </div>
    
</form>

mvc/Views/Ogrenci/Guncelle.cshtml
@model Ogrenci

<form asp-controller="Ogrenci" asp-action="Guncelle" method="post">
    <input type="hidden" asp-for="OgrenciId">
    <div asp-validation-summary="All"></div>
    <div class="form-group">
        <label asp-for="OgrenciAdi"></label>
        <input asp-for="OgrenciAdi" class="form-control">
    </div>
    
    <div class="form-group">
        <label asp-for="OgrenciSoyadi"></label>
        <input asp-for="OgrenciSoyadi" class="form-control">
    </div>
    <div class="form-group">
        <label asp-for="SinifId"></label>
        <select name="SinifId" class="form-control" asp-items="@(new SelectList(ViewBag.sinifListesi,"Value","Text"))">
            <option value="">
                Bir Sınıf Seçiniz

            </option>
        </select>
    </div>
    <div class="form-group">
        <button type="submit" class="btn btn-success">Kaydet</button>
    </div>

</form>

mvc/Views/Ogrenci/Index.cshtml
@model List<OgrenciSinifModel>
<table class="table">
    <tr>
        <th>Öğrenci ID</th>
        <th>Öğrenci Adi</th>
        <th>Öğrenci Soyadı</th>
        <th> # </th>
    </tr>
    @foreach (var ogrenciSinif in Model)
    {
        <tr>
            <td>@ogrenciSinif.OgrenciId</td>
            <td>@ogrenciSinif.OgrenciAdi</td>
            <td>@ogrenciSinif.OgrenciSoyadi</td>
            <td>@ogrenciSinif.SinifAdi</td>
            <td>@ogrenciSinif.SinifKodu</td>
            <td>
                <a class="btn btn-primary" href="/Ogrenci/Guncelle/@ogrenciSinif.OgrenciId">Güncelle</a>
                <a class="btn btn-primary" href="/Ogrenci/Sil/@ogrenciSinif.OgrenciId">Sil</a>
            </td>
        </tr>
    }
</table>

mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - mvc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/mvc.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">mvc</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Ogrenci" asp-action="Index">Öğrenciler</a>
                        </li
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Ogrenci" asp-action="Ekle">Öğrenci Ekle</a>
                        </li
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Sinif" asp-action="Index">Sınıflar</a>
                        </li
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Sinif" asp-action="Ekle">Sınıf Ekle</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - mvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

mvc/Views/Sinif/Ekle.cshtml
@model Sinif

<form asp-controller="Sinif" asp-action="Ekle" method="post">
    <div asp-validation-summary="All"></div>
    <div class="form-group">
        <label asp-for="SinifAdi"></label>
        <input asp-for="SinifAdi" class="form-control">
    </div>
    <div class="form-group">
        <label asp-for="SinifKodu"></label>
        <input asp-for="SinifKodu" class="form-control">
    </div>
    <div class="form-group">
        <button type="submit" class="btn btn-success">Kaydet</button>
    </div>
    
</form>

mvc/Views/Sinif/Guncelle.cshtml
@model Sinif

<form asp-controller="Sinif" asp-action="Guncelle" method="post">
    <input type="hidden" asp-for="SinifId">
    <div asp-validation-summary="All"></div>
    <div class="form-group">
        <label asp-for="SinifAdi"></label>
        <input asp-for="SinifAdi" class="form-control">
    </div>
    <div class="form-group">
        <label asp-for="SinifKodu"></label>
        <input asp-for="SinifKodu" class="form-control">
    </div>
    <div class="form-group">
        <button type="submit" class="btn btn-success">Kaydet</button>
    </div>

</form>

mvc/Views/Sinif/Index.cshtml
@model List<Sinif>
<table class="table">
    <tr>
        <th>Sinif ID</th>
        <th>Sinif Adi</th>
        <th>Sinif Kodu</th>
        <th> # </th>
    </tr>
    @foreach (var sinif in Model)
    {
        <tr>
            <td>@sinif.SinifId</td>
            <td>@sinif.SinifAdi</td>
            <td>@sinif.SinifKodu</td>
            <td>
                <a class="btn btn-primary" href="/Sinif/Guncelle/@sinif.SinifId">Güncelle</a>
                <a class="btn btn-primary" href="/Sinif/Sil/@sinif.SinifId">Sil</a>
            </td>
        </tr>
    }
</table>